extends FW_EffectCommand

class_name FW_UniversalEffectCommand

@export var effect_resource: Resource  # Will be EffectResource
@export var context_vars: Dictionary = {}

func _init(resource: Resource = null, context: Dictionary = {}) -> void:
	if resource:
		effect_resource = resource
		context_vars = context
		command_type = resource.effect_type
		description = resource.name
		log_message = ""  # Will be generated by the resource

func execute() -> void:
	if not effect_resource:
		push_error("UniversalEffectCommand: No effect resource provided")
		return
	# Inject attacker/target names into context for template resolution if missing
	if GDM.game_manager:
		var is_player_turn = context_vars.get("is_player_turn", GDM.game_manager.turn_manager.is_player_turn())
		if not context_vars.has("attacker"):
			context_vars["attacker"] = GDM.player.character.name if is_player_turn else GDM.monster_to_fight.name
		if not context_vars.has("target"):
			context_vars["target"] = GDM.monster_to_fight.name if is_player_turn else GDM.player.character.name

	# Attach the context onto the resource for log aggregation tools to inspect
	if effect_resource.has_method("set"):
		# store in a common slot so CombatLogBus can read it
		effect_resource.set("last_context", context_vars)

	# Let the resource handle its own execution and logging
	# EffectResource will call CombatManager.apply_damage_with_checks and its logs; when called from commands we suppress duplicate EventBus publishes there
	effect_resource.execute(context_vars)

	# If the resource produced a prepared log, publish it now in queue order
	var lm = null
	if effect_resource:
		lm = effect_resource.get("last_log_message")
	if lm != null and lm != "":
		var li = null
		if effect_resource:
			li = effect_resource.get("last_log_icon")
		if li != null:
			EventBus.publish_combat_log_with_icon.emit(lm, li)
		else:
			EventBus.publish_combat_log.emit(lm)
		# clear to avoid re-publishing
		if effect_resource:
			effect_resource.set("last_log_message", "")
			effect_resource.set("last_log_icon", null)

func can_execute() -> bool:
	return effect_resource != null
